RESULTS_EXTRACT_COLUMNS = [
    "nome_do_arquivo",
    "id_taxonomia",
    "nome_taxonomia",
    "id_amostra",
    "tipo",
    "categoria",
    "subcategoria",
    "parameter",
    "resultado",
    "acm_resultado_tratado",
    "acm_qualificador",
    "acm_unidade",
    "local",
    "data_inicio",
    "conama",
    "acm_conama_operador",
    "acm_conama_minimo",
    "acm_conama_maximo",
    "acm_conama_unidade",
    "copam_cerh",
    "acm_copam_cerh_operador",
    "acm_copam_cerh_minimo",
    "acm_copam_cerh_maximo",
    "acm_copam_cerh_unidade",
    "ld",
    "acm_ld_minimo",
    "acm_ld_maximo",
    "acm_ld_unidade",
    "lq",
    "acm_lq_minimo",
    "acm_lq_maximo",
    "acm_lq_unidade",
    "referencia",
    "incerteza",
    "acm_incerteza_valor",
    "acm_incerteza_unidade",
    "numero_cq",
    "duplicata",
    "faixa_aceitacao",
    "acm_faixa_aceitacao_operador",
    "acm_faixa_aceitacao_minimo",
    "acm_faixa_aceitacao_maximo",
    "acm_faixa_aceitacao_unidade",
    "variacao_percentual",
    "quantidade_adicionada",
    "recuperacao_percentual",
]

SAMPLE_COLUMNS = [
    "nome_do_arquivo",
    "id_taxonomia",
    "nome_taxonomia",
    "id_amostra",
    "identificacao_amostra",
    "tipo_amostra",
    "criterio_conformidade",
    "data_coleta",
    "dh_coleta",
    "data_publicacao",
    "dh_publicacao",
    "data_recebimento",
    "dh_recebimento",
    "observacoes",
    "dh_inicio_atividade",
    "localizacao",
    "latitude",
    "longitude",
    "coordenadas",
    "clima_ultimas_24h",
    "clima",
    "tipo_coleta",
    "responsavel_amostra",
    "planejamento_amostragem",
    "descricao_nao_conformidade",
]

CLIENT_COLUMNS = [
    "nome_do_arquivo",
    "id_taxonomia",
    "nome_taxonomia",
    "id_amostra",
    "proposta_comercial",
    "cliente",
    "cnpj_cpf",
    "contato",
    "telefone",
    "endereco",
]

PACKAGING_PRESERVATIVES_COLUMNS = [
    "nome_do_arquivo",
    "id_taxonomia",
    "nome_taxonomia",
    "id_amostra",
    "identificacao_amostra",
    "embalagem",
    "volume",
    "preservacao",
    "metodos",
]

TABLE_EXTRACTION_AUDIT_COLUMNS = [
    "nome_do_arquivo",
    "id_taxonomia",
    "nome_taxonomia",
    "pagina",
    "tabela_indice",
    "categoria",
    "subcategoria",
    "tipo_registro",
    "modo_auditoria",
    "cabecalho_detectado",
    "colunas_detectadas",
    "colunas_mapeadas",
    "colunas_sem_mapeamento",
    "campos_esperados",
    "campos_obrigatorios_ausentes",
    "campos_opcionais_ausentes",
    "usou_fallback",
    "status",
    "observacao",
]

LAYOUT_FIELD_KEYS = [
    "resultado_col",
    "unidade_col",
    "data_inicio_col",
    "conama_col",
    "copam_cerh_col",
    "ld_col",
    "lq_col",
    "referencia_col",
    "incerteza_col",
    "numero_cq_col",
    "duplicata_col",
    "faixa_aceitacao_col",
    "variacao_percentual_col",
    "quantidade_adicionada_col",
    "recuperacao_percentual_col",
]

TIPO_LABELS = {
    "AMOSTRA": "Amostra",
    "BRANCO": "Branco",
    "DUPLICATA": "Duplicata",
    "RECUPERACAO": "Recupera\u00e7\u00e3o",
}

