RESULTS_EXTRACT_COLUMNS = [
    "nome_do_arquivo",
    "template_id",
    "tipo_laudo",
    "id_sample",
    "tipo",
    "categoria",
    "subcategoria",
    "parameter",
    "resultado",
    "resultado_tratado",
    "qualificador",
    "unidade",
    "local",
    "data_inicio",
    "criterio_conformidade",
    "lq_original",
    "lq_minimo",
    "lq_maximo",
    "lq_unidade",
    "referencia",
    "incerteza_original",
    "incerteza_valor",
    "incerteza_unidade",
    "numero_cq",
    "duplicata",
    "faixa_aceitacao_original",
    "faixa_aceitacao_operador",
    "faixa_aceitacao_minimo",
    "faixa_aceitacao_maximo",
    "faixa_aceitacao_unidade",
    "variacao_percentual",
    "quantidade_adicionada",
    "recuperacao_percentual",
]

SAMPLE_COLUMNS = [
    "nome_do_arquivo",
    "template_id",
    "tipo_laudo",
    "id_amostra",
    "tipo_amostra",
    "criterio_conformidade",
    "data_coleta",
    "dh_coleta",
    "data_publicacao",
    "dh_publicacao",
    "data_recebimento",
    "dh_recebimento",
    "observacoes",
    "dh_inicio_atividade",
    "localizacao",
    "latitude",
    "longitude",
    "coordenadas",
    "clima_ultimas_24h",
    "clima",
    "tipo_coleta",
    "responsavel_amostra",
    "planejamento_amostragem",
    "descricao_nao_conformidade",
]

CLIENT_COLUMNS = [
    "nome_do_arquivo",
    "template_id",
    "tipo_laudo",
    "id_amostra",
    "proposta_comercial",
    "cliente",
    "cnpj_cpf",
    "contato",
    "telefone",
    "endereco",
]

LAYOUT_FIELD_KEYS = [
    "resultado_col",
    "unidade_col",
    "data_inicio_col",
    "criterio_conformidade_col",
    "lq_col",
    "referencia_col",
    "incerteza_col",
    "numero_cq_col",
    "duplicata_col",
    "faixa_aceitacao_col",
    "variacao_percentual_col",
    "quantidade_adicionada_col",
    "recuperacao_percentual_col",
]

TIPO_LABELS = {
    "AMOSTRA": "Amostra",
    "BRANCO": "Branco",
    "DUPLICATA": "Duplicata",
    "RECUPERACAO": "Recupera\u00e7\u00e3o",
}

